- tests/snaps/vine/fail/atypical.txt
- vine/src/checker/display_type.rs
`checker/display_type` was not properly updated in #93, and was still printing types with their old names.
> vine: fix type display

- tests/programs/aoc_2024/day_04.vi
- tests/programs/aoc_2024/day_05.vi
- tests/programs/aoc_2024/day_08.vi
- tests/programs/aoc_2024/day_10.vi
- tests/programs/aoc_2024/day_12.vi
- tests/programs/aoc_2024/day_18.vi
- tests/programs/aoc_2024/day_24.vi
- tests/programs/inverse.vi
- tests/snaps/vine/fail/atypical.txt
- tests/snaps/vine/fail/hallo_world.txt
- tests/snaps/vine/fail/informal.txt
- tests/snaps/vine/fail/is_not.txt
- tests/snaps/vine/fail/visibility.txt
- vine/src/ast.rs
- vine/src/checker.rs
- vine/src/checker/check_expr.rs
- vine/src/checker/check_pat.rs
- vine/src/checker/typeof_def.rs
- vine/src/distiller.rs
- vine/src/distiller/control_flow.rs
- vine/src/distiller/pattern_matching.rs
- vine/src/fmt.rs
- vine/src/parser.rs
- vine/src/visit.rs
- vine/std/array.vi
- vine/std/list.vi
- vine/std/map.vi
- vine/std/n64.vi
- vine/std/rng.vi
- vine/std/tuple.vi
- resolves #128
this allows things like
```rs
// before:
fn foo((a, b): (N32, String), Bar(x, y): Bar[Baz])
// after:
fn foo((a: N32, b: String), Bar[Baz](x, y))
```
> vine: make annotations a kind of pattern

- docs/theme/index.hbs
> docs: fix indentation in code blocks

- tests/programs/segmented_sieve.vi
- tests/snaps/vine/segmented_sieve/compiled.iv
- tests/snaps/vine/segmented_sieve/stats.txt
Fixes an off-by-one error that caused it to identify `9` as a prime number when supplied a max of `10`.
Thanks @nilscrm for finding this issue.
> fix off-by-one error in `segmented_sieve.vi`

- ivy/src/lexer.rs
- vine/src/lexer.rs
Before this change, the lexer would complain about `\r\n` in files checked out on Windows:
```
error \\?\C:\Users\Gordon\Source\Repos\Vine\vine\vine\examples\hello_world.vi:1:1 - lexing error
error \\?\C:\Users\Gordon\Source\Repos\Vine\vine\vine\std\std.vi:1:1 - lexing error
```
This change allows `\r` between tokens in the Ivy and Vine lexers.
> Allow the lexer to work on Windows by permitting `\r` between tokens

- .gitignore
- cli/src/vine_cli.rs
- flake.lock
- flake.nix
Adds `flake.nix` to project, which allows one to build vine trivially with nix ecosystem.  For example, I can consume the project with this
```flake.nix
{
inputs = {
vine.url = "https://github.com/VineLang/vine";
vine.inputs.nixpkgs.follows = "nixpkgs"; # I can override which other inputs and build inputs are used
};
{ vine, ... }:
}
```
I can use `nix flake update` to pull latest vine versions and benefit from binary caching on all the rust components and libraries as well. 
Similarly, anyone with nix could run any "version" of vine by pointing `nix run` at it:
```bash
nix run git+https://github.com/VineLang/vine # with some branch or sha ref, for instance
```
Motivations:
1.  Because vine is unversioned currently and has no other release process.  I'm already tinkering with vine on my …
> meta: add nix flake build support

- docs/src/features/types/index.md
Previously it was (erroneously) linked to the primitive types page.
> docs: fix standard types link

- tests/programs/string_ops.vi
- tests/snaps/vine/aoc_2024/day_21/compiled.iv
- tests/snaps/vine/string_ops/compiled.iv
- tests/snaps/vine/string_ops/output.txt
- tests/snaps/vine/string_ops/stats.txt
- tests/tests.rs
- vine/std/unicode/String.vi
Currently, like `strip_prefix`, `starts_with` takes the prefix as reference and I can see reasons for doing this especially when reusing a prefix multiple times and repeatedly having diverging prefixes.
However, I can also see reasoning for why is might be nice to have `starts_with` take the prefix as value for performance reasons and better parallelism. Wdyt?
> std: add starts_with method to String

- .github/workflows/checks.yml
- dprint.json
Files get formatted instantly rather than in ~1s when using cargo and formatting also continues vine doesn't build while e.g. working on the compiler.
The downside is that changes to the formatter itself require a `cargo install` to propergate but I think that is reasonable and justified by the benefits.
> tooling: use installed vine bin for formatting

- vine/std/ops/comparison.vi
`ne_from_eq` is currently unused and I would argue that it is always easier to simply implement `ne` from `eq` directly as is done in #231 than to use `ne_from_eq`.
> std: remove ne_from_eq

- tests/programs/string_ops.vi
- tests/snaps/vine/string_ops/output.txt
- tests/snaps/vine/string_ops/stats.txt
- vine/std/data/List.vi
When lists or strings of the same length were compared that are not equal, not dropping the iterator deletes part of the string.
> std: fix iterator dropping in List eq

- tests/programs/repl/i32_misc.vi
- tests/snaps/vine/repl/i32_misc.repl.vi
- vine/std/numeric/I32.vi
Parsing of non-negative ints should also work with no plus sign in the front. No plus sign is probably even the more common case. My current case: Parsing exponents in scientific float notation (e.g. 1e3).
> std: parse ints without sign

- cspell.json
- tests/programs/primenesses.vi
- tests/programs/repl/misc.vi
- tests/snaps/vine/primenesses/output.txt
- tests/snaps/vine/primenesses/stats.txt
- tests/snaps/vine/repl/misc.repl.vi
- tests/tests.rs
- vine/src/ast.rs
- vine/src/chart.rs
- vine/src/charter.rs
- vine/src/checker/check_expr.rs
- vine/src/diag.rs
- vine/src/distiller.rs
- vine/src/distiller/control_flow.rs
- vine/src/fmt.rs
- vine/src/parser.rs
- vine/src/visit.rs
- vine/std/logical/Result.vi
Adds a basic version of the try (`?`) operator. Only works on `Result`s for now, and does no casting of the error type. There is no `try {}` block yet either.
Partially implements #230
Drafted due to dependency on #246
> vine: add basic try operator

- tests/programs/aoc_2024/day_12.vi
- tests/programs/par.vi
- tests/programs/the_greatest_show.vi
- vine/src/charter.rs
- vine/src/diag.rs
- vine/std/data/Array.vi
- vine/std/data/List.vi
- vine/std/data/Map.vi
- vine/std/debug/Show.vi
- vine/std/logical/Bool.vi
- vine/std/logical/Option.vi
- vine/std/logical/Result.vi
- vine/std/numeric/F32.vi
- vine/std/numeric/I32.vi
- vine/std/numeric/N32.vi
- vine/std/numeric/N64.vi
- vine/std/ops/ops.vi
- vine/std/ops/range.vi
- vine/std/ops/vectorized.vi
- vine/std/unicode/Char.vi
- vine/std/unicode/String.vi
Currently, impl fns can be marked as methods, but this does not really affect anything; it is whether the trait fn is marked as a method that matters. This requires that impl fns not be marked as methods (much like they cannot have visibility).
> vine: disallow marking impl fns as methods

- tests/programs/repl/misc.vi
- tests/snaps/vine/repl/misc.repl.vi
- vine/src/checker.rs
The checker was previously looking at the number of implementation parameters declared in the AST, and thus failing to account for the impl parameters from the `+`/`?`/`*` annotation. This was not being caught before as it would only be encountered for functions with these impl parameters.
> vine: fix checker bug re fork/drop impl param shorthand

- cli/src/vine_cli.rs
Not sure why this wasn't there before.
> cli: add `--no-opt` flag to `vine run`

- cli/src/vine_cli.rs
- lsp/src/lib.rs
- tests/programs/aoc_2024/day_12.vi
- tests/programs/aoc_2024/day_18.vi
- tests/programs/lambda.vi
- tests/programs/repl/misc.vi
- tests/snaps/vine/fail/atypical.txt
- tests/snaps/vine/fail/is_not.txt
- tests/snaps/vine/repl/misc.repl.vi
- vine/src/compiler.rs
- vine/src/components/analyzer.rs
- vine/src/components/distiller.rs
- vine/src/components/distiller/control_flow.rs
- vine/src/components/distiller/pattern_matching.rs
- vine/src/components/emitter.rs
- vine/src/components/resolver.rs
- vine/src/components/resolver/resolve_expr.rs
- vine/src/components/resolver/resolve_expr/coerce_expr.rs
- vine/src/components/resolver/resolve_pat.rs
- vine/src/structures/diag.rs
- vine/src/structures/tir.rs
- vine/src/structures/vir.rs
- vine/src/tools/repl.rs
- vine/std/logical/Option.vi
- vine/std/logical/Result.vi
- vine/std/unsafe.vi
Resolves #134 
The error message is not very helpful at the moment, but this can be improved in the future. Better than just silently evaluating to an eraser node, at any rate.
> vine: require exhaustive pattern matching 

- ivm/src/heap.rs
Fixes an issue I encounter not infrequently:
- the IVM requests a terabyte of virtual memory, which the OS happily provides
- a buggy Ivy program causes an infinite allocation loop
- IVM fills its virtual memory at the speed of light
- unable to keep up, the kernel panics
Four gigabytes ought to be enough for anyone ;)
> ivm: lower max heap size

- docs/src/features/usual.md
Previously the link caused the `types/standard` page not to load CSS correctly. I grepped the source but couldn't find similarly broken paths.
> docs: fix double slash

- tests/programs/the_greatest_show.vi
- tests/snaps/vine/fail/atypical.txt
- tests/snaps/vine/fail/informal.txt
- tests/snaps/vine/fail/is_not.txt
- tests/snaps/vine/repl/misc.repl.vi
- tests/snaps/vine/repl/objects.repl.vi
- tests/snaps/vine/the_greatest_show/stats.txt
- vine/src/compiler.rs
- vine/src/components/distiller.rs
- vine/src/components/emitter.rs
- vine/src/components/finder.rs
- vine/src/components/normalizer.rs
- vine/src/components/resolver.rs
- vine/src/components/specializer.rs
- vine/src/features/builtin.rs
- vine/src/features/fn_.rs
- vine/src/features/generics.rs
- vine/src/features/impl_.rs
- vine/src/features/path.rs
- vine/src/structures/checkpoint.rs
- vine/src/structures/resolutions.rs
- vine/src/structures/specializations.rs
- vine/src/structures/tir.rs
- vine/src/structures/vir.rs
- vine/std/debug/Show.vi
- vine/std/derive.vi
- vine/std/ops/comparison.vi
- vine/std/ops/flex.vi
- vine/std/std.vi
Implements the `Tuple` and `Object` traits from #169, allowing traits to be implemented for all tuple and object types, as well as a `Composite` trait that abstracts over `Tuple` and `Object` for things like `Fork` and `Drop` which do not need to differentiate between tuples and objects. These traits are now used for implementing `Fork`, `Drop`, `Show`, `Eq`, and `Ord`.
> vine: tuple/object impl derivation

- tests/programs/aoc_2024/day_12.vi
- tests/programs/aoc_2024/day_19.vi
- tests/programs/aoc_2024/day_24.vi
- tests/programs/repl/misc.vi
- tests/programs/repl/string_ops.vi
- tests/programs/specializations.vi
- tests/snaps/vine/repl/misc.repl.vi
- tests/snaps/vine/repl/string_ops.repl.vi
This was previously used to turn values into places, but as of #302 this now happens automatically.
> vine: remove use of `(expr; _)`
